### PR TITLE
Fix infinite scrolling

### LINKED ISSUE #26: Search scroll auto load broken

### PR DESCRIPTION
**Pull request by joextodd**
Closes #26

### CODE REVIEW

File: src/mixins/search.js [hunk 1]
```diff
@@ -19,7 +19,6 @@ export const Search = () => ({
       a.fetchResults()
     },
     fetchResults: (s,a,d) => {
-      (s.searchString.length || s.searchResults.length === 0) &&
```
Comment (lukejacksonn) [inline src/mixins/search.js:22]: This was here to make sure we only searched when there was a search term or there were no current search results. I guess you have tested these scenarios. If all good then :shipit:

**Review by lukejacksonn — APPROVED** [review]

File: src/mixins/search.js (hunk 1 above)
Comment (joextodd) [reply src/mixins/search.js:22]: Yeah it still only searched on page load, and when you reach the bottom of the page without it.
